# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  integrate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${HEAD_BRANCH})"
      id: extract_branch
      env:
        HEAD_BRANCH: ${{ github.head_ref }}
      if: github.event_name == 'pull_request'

    - name: Validate branch name
      run: |
        echo "${{ steps.extract_branch.outputs.branch }}"
